AllCops:
  DisabledByDefault: true
  Include: 
    - 'app/**/*.rb'
    - 'spec/features/*.rb'
    - 'spec/models/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: disable

Layout:
  Enabled: true

Lint:
  Enabled: true

Naming:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/Semicolon:
  Enabled: true