name: Ruby linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: RuboCop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
